---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s | %(levelname)s | %(message)s"

handlers:
    console:
        class: dst.utils.TqdmLoggingHandler
        level: DEBUG
        formatter: simple

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: info.log
        backupCount: 2
        encoding: utf8

root:
    level: INFO
    handlers: 
      - console
      - file_handler
...